version: 0.2
phases:
  install:
    commands:
    - |
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y  software-properties-common
      LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
      apt-get update
      apt-get install -y php7.1 \
               php7.1-xml \
               php7.1-xmlrpc \
               php7.1-zip \
               php7.1-mysql \
               php7.1-mbstring \
               php7.1-mcrypt \
               php7.1-gd \
               php7.1-opcache \
               php7.1-dom \
               php7.1-bcmath \
               php7.1-curl \
               unzip \
               jq
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php composer-setup.php ;
      php -r "unlink('composer-setup.php');" ;
      mv composer.phar /usr/local/bin/composer
      composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}

  pre_build:
    commands:
    - TAG=$(echo $CODEBUILD_SOURCE_VERSION)

  build:
    commands:
    - echo Build started on `date`
    - echo Installing composer deps
    - composer install --quiet --no-progress --no-suggest
    - npm install -s
    - for dir in ./nova-components/*/ ; do (cd "$dir" && npm install && npm run prod); done
    - npm run prod

  post_build:
    commands:
    - echo Build completed on `date`
    # - ./vendor/bin/phpunit
    - echo $(TAG) > version.txt

artifacts:
  files:
  - .ebextensions/**/*
  - app/**/*
  - artisan
  - bootstrap/**/*
  - config/**/*
  - composer.json
  - database/**/*
  - helpers/**/*
  - nova-components/**/*
  - public/**/*
  - resources/**/*
  - routes/**/*
  - storage/**/*
  - vendor/**/*
  discard-paths: no
  name: $TAG